config/routes.rb
RailsGame::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", confirmations: 'confirmations' }

  resources :dashboard
  resources :games do
    resources :ratings
  end
  resources :tournaments do
    get '/simulate' => 'tournaments#simulate'
  end
  resources :users
  resources :participations

  resources :notifications, only: [:index] do
    post :mark_as_read, on: :collection
    post :mark_as_read, on: :member
  end 

  get '/rankings' => 'users#ranking'

  root to: 'dashboard#index'
end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :user
  belongs_to :games_tournament
  
  has_many :matchs

end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController

    def create 
        @participation = Participation.new

        participation_params_form

        redirect_to participations_path
    end

    def index
        @tournaments = Tournament.all
    end

    def new
        @participation = Participation.new

        @tournament = Tournament.find(params[:tournament])
        @game = Game.find(params[:game])
        @user = User.find(params[:user])
    end

    private 
        def participation_params_form
            @user = User.find(params[:participation][:user])

            @user.inscription(params[:participation][:game], params[:participation][:tournament])

        end
end

app/helpers/participations_helper.rb
module ParticipationsHelper

    def select_player_form
        User.all.collect {|u| [u.username, u.id]}
    end
end

app/views/participations/_form.html.haml
= form_for(@participation) do |f|
    %ul
        - @participation.errors.full_messages.each do |error|
            %li= error
    .form-group
        = f.label :tournament
        %br/
        = @tournament.name
        = f.hidden_field :tournament, :value => @tournament.id, :readonly => true
    .form-group
        = f.label :game
        %br/
        = @game.title
        = f.hidden_field :game, :value => @game.id, :readonly => true
    .form-group
        = f.label :user
        %br/
        = @user.email
        = f.hidden_field :user, :value => @user.id, :readonly => true
    .form-group
        = f.submit

app/views/participations/index.html.haml
%h3 All Participations

.row
    .col-md-6
        - @tournaments.each do |tournament|
            = link_to tournament.name, tournament_path(tournament)
            - tournament.games.each do |game|
                %li.list-group-item
                    .row
                        .col-md-6
                            = link_to game.title, game_path(game)
                        .col-md-6
                            = link_to "Inscription", new_participation_path(:game => game, :tournament => tournament, :user => current_user)
                    

app/views/participations/new.html.haml
%h3 New inscription
= render partial: 'form'