config/routes.rb
RailsGame::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", confirmations: 'confirmations' }

  resources :dashboard
  resources :games do
    resources :ratings
  end
  resources :tournaments do
    get '/simulate' => 'tournaments#simulate'
  end
  resources :users
  resources :participations

  resources :notifications, only: [:index] do
    post :mark_as_read, on: :collection
    post :mark_as_read, on: :member
  end 

  get '/rankings' => 'users#ranking'

  root to: 'dashboard#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :street, :city, :state, :country, :nb_victories, :nb_defeats, :total_points, :avatar, :email, :password, :password_confirmation, :remember_me, :address

  has_attached_file :avatar
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  validates :email, :presence => true, :email => true

  has_many :participations
  has_many :games_tournaments, through: :participations
  has_many :matchs, through: :participations
  has_many :games, through: :games_tournaments
  has_many :tournaments, through: :games_tournaments
  has_many :ratings
  has_many :notifications, foreign_key: :recipient_id

  geocoded_by :address   # can also be an IP address
  after_validation :geocode     # auto-fetch coordinates

  def add_score=(score)
    case score
    when Match::WIN
      self.nb_victories += 1
      self.total_points += score
    when Match::DRAW
      self.total_points += score
    else
      self.nb_defeats += 1
    end

    self.save
  end

  def address
    [street, city, state, country].compact.join(', ')
  end

  def inscription(game, tournament)
    found_games_tournament = GamesTournament.where(game_id: game, tournament_id: tournament)
    puts found_games_tournament
    self.games_tournaments += found_games_tournament
  end
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end      
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
       @user = User.from_omniauth(request.env["omniauth.auth"])
       sign_in_and_redirect @user      
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def create
      @user = User.new
  
      user_params_form
  
      flash.notice = "User '#{@user.username}' Created!"
    end
  
    def destroy
      @user = User.find(params[:id])
  
      @user.destroy
  
      redirect_to users_path()
  
      flash.notice = "User '#{@user.username}' Deleted!"
    end
  
    def edit
      @user = User.find(params[:id])
    end
  
    def index
      @users = User.order('username asc').all
    end
  
    def new
      @user = User.new
    end

    def ranking
      @victories = User.order('nb_victories desc').all
      @defeats = User.order('nb_defeats desc').all
      @points = User.order('total_points desc').all
    end
  
    def show
      @user = User.find(params[:id])

      puts "====================================="
      puts @user.geocode

      @tournaments = Tournament.near([@user.latitude, @user.longitude], 50)

      puts @tournaments

      @tournaments.each do |t|
        puts t.name 
      end

    end
  
    def update
      @user = User.find(params[:id])
  
      user_params_form
  
    end
  
    private
      def user_params_form

        if(check_user_params)
          @user.username = params[:user][:username]
          @user.street = params[:user][:street]
          @user.city = params[:user][:city]
          @user.state = params[:user][:state]
          @user.country = params[:user][:country]
          @user.avatar = params[:user][:avatar]
    
          @user.save
    
          redirect_to user_path(@user)

          flash.notice = "User '#{@user.username}' Updated!"
        else

          redirect_to edit_user_path(@user)

          flash.notice = "The edit had a problem. Please try again"
        end
        
      end

      def check_user_params
        if !check_username(params[:user][:username])
          puts "Username"
          return false
        elseif !check_street(params[:user][:street])
          puts "Street"
          return false
        elseif !check_address(params[:user][:city])
          puts "City"
          return false
        elseif !check_address(params[:user][:state])
          puts "State"
          return false
        elseif !check_address(params[:user][:country])
          puts "Country"
          return false
        else
          return true
        end
      end

      def check_object(object)
        return !object.empty?
      end

      def check_username(username)
        return check_object(username) && !username.match(/^[aA-zZ0-9]+([-._][a-z0-9]+)*$/i).nil?
      end

      def check_street(street)
        return check_object(street) && !street.match(/^[aA-zZ0-9]+([\s-][aA-zZ0-9]+)*$/i).nil?
      end

      def check_address(address)
        return check_object(address) && !address.match(/^[aA-zZ]+([-][aA-zZ]+)*$/i).nil?
      
      end

  end
  

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
.row
  .col-md-3
  .col-md-6
    .well
      = form_for(@user, html: {multipart: true, class: "form-horizontal", id: "user-form"}) do |f|
        %fieldset
          %legend 
            - if @user.id.nil?
              Add an user
            - else
              Edit 
              = @user.username
          %ul
            - @user.errors.full_messages.each do |error|
              %li= error
          .form-group
            = f.label :username, class: 'col-lg-2 control-label'
            .col-lg-10.field
              = f.text_field :username, class: 'form-control', id: 'user-username'
          .form-group
            = f.label :street, class: 'col-lg-2 control-label'
            .col-lg-10.field
              = f.text_field :street, class: 'form-control', id: 'user-street'
          .form-group
            = f.label :city, class: 'col-lg-2 control-label'
            .col-lg-10.field
              = f.text_field :city, class: 'form-control', id: 'user-city'
          .form-group
            = f.label :state, class: 'col-lg-2 control-label'
            .col-lg-10.field
              = f.text_field :state, class: 'form-control', id: 'user-state'
          .form-group
            = f.label :country, class: 'col-lg-2 control-label'
            .col-lg-10.field
              = f.text_field :country, class: 'form-control', id: 'user-country'    
          .form-group
            - if @user.avatar.exists?
              = image_tag @user.avatar.url
              %br/
            = f.label :avatar, "Attach an Image", class: 'col-lg-4 control-label'
            .col-lg-8
            = f.file_field :avatar, class: 'form-control-file'
          .form-group
            .row
              .col-md-6.col-md-offset-1
                - if @user.id.nil?
                  = link_to "Back to Users", users_path(), class: 'btn btn-default'
                - else
                  = link_to "Back to User", user_path(@user), class: 'btn btn-default'
              .col-md-4.col-md-offset-1
                = f.submit class: 'btn btn-primary'

app/views/users/edit.html.haml
= render partial: 'form'

app/views/users/index.html.haml
%h1{style: "text-align:center"} All Users

.row
	.col-md-3
	.col-md-6
		- if current_user.try(:admin?)
			= link_to "Add a new user", new_user_path, class: 'btn btn-link'
		.well
			%ul.list-group
				- @users.each do |user|
					%li.list-group-item
						.row
							.col-md-9
								%h4
									= user.username
							.col-md-3
								.btn-group
									.btn-group
										- if can? :create, User
											%a.btn.btn-default.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", href: "#"}
												Actions	
												%span.caret
											%ul.dropdown-menu
												%li
													= link_to "See Profile", user_path(user)
												%li
													= link_to "Edit Profile", edit_user_path(user)
												%li
													= link_to "Delete User", user_path(user), method: :delete, data: {confirm: "Really delete " + user.email + "?"}	
										- else
											= link_to "See profile", user_path(user)								

app/views/users/new.html.haml
= render partial: 'form'

app/views/users/ranking.html.haml
%h3 Statistics
.row
	.col-md-4
		%h4 Victories :
		%table.table
			%thead
				%tr
					%th Name
					%th Victories
			%tbody
				- @victories.each do |user|
					%tr
						%td
							= user.username
						%td
							= user.nb_victories
						%td
	.col-md-4						
		%h4 Defeats :
		%table.table
			%thead
				%tr
					%th Name
					%th Defeats
			%tbody
				- @defeats.each do |user|
					%tr
						%td
							= user.username
						%td
							= user.nb_defeats
						%td
	.col-md-4					
		%h4 Total Points :
		%table.table
			%thead
				%tr
					%th Name
					%th Points
			%tbody
				- @points.each do |user|
					%tr
						%td
							= user.username
						%td
							= user.total_points
						%td						

app/views/users/show.html.haml
.container
  %h1{style:"text-align:center"}
    Profile of
    = @user.username

  .row
    .col-lg-4
    .col-lg-4
      .btn-group.btn-group-justified{style:"text-align:center"}
        - if can? :update, @user
          = link_to "edit", edit_user_path(@user), class: 'btn btn-link'
        - if can? :destroy, @user
          = link_to "delete", user_path(@user), method: :delete, data: {confirm: "Really delete the user?"}, class: 'btn btn-link'
        = link_to "Back to Users", users_path, class: 'btn btn-link'
  %hr
  .row
    - if @user.avatar.exists?
      .col-md-6
        = image_tag @user.avatar.url
      .col-md-6
        .well
          %h3 Personal Information
          %p 
            %strong Street :
            = @user.street 
          %p
            %strong City : 
            = @user.city
          %p
            %strong State :
            = @user.state
          %p
            %strong Country :
            = @user.country
          %h3 Statistics
          %p
            %strong Number of victories :
            = @user.nb_victories
          %p
            %strong Number of defeats :
            = @user.nb_defeats
          %p
            %strong Total points :
            = @user.total_points
    - else
      .col-md-3
      .col-md-6
        .well
          %h3 Personal Information
          %p 
            %strong Street :
            = @user.street 
          %p
            %strong City : 
            = @user.city
          %p
            %strong State :
            = @user.state
          %p
            %strong Country :
            = @user.country
          %h3 Statistics
          %p
            %strong Number of victories :
            = @user.nb_victories
          %p
            %strong Number of defeats :
            = @user.nb_defeats
          %p
            %strong Total points :
            = @user.total_points
          %p
            %strong Nearby Tournaments :
            %lu.list-group
              - for location in @tournaments
                %li
                  = link_to location.name, location
                  (#{location.distance.to_f.round(2)} miles)
  .row.well
    .col-md-6
      %h3 List of participating tournaments
      %lu.list-group
        - @user.tournaments.uniq.each do |t|
          %li.list-group-item
            = link_to t.name, tournament_path(t)
    .col-md-6  
      %h3 List of games played
      %lu.list-group
        - @user.games.uniq.each do |g|
          %li.list-group-item
            = link_to g.title, game_path(g)