config/routes.rb
RailsGame::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", confirmations: 'confirmations' }

  resources :dashboard
  resources :games do
    resources :ratings
  end
  resources :tournaments do
    get '/simulate' => 'tournaments#simulate'
  end
  resources :users
  resources :participations

  resources :notifications, only: [:index] do
    post :mark_as_read, on: :collection
    post :mark_as_read, on: :member
  end 

  get '/rankings' => 'users#ranking'

  root to: 'dashboard#index'
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  #after_create :create_notifications

  has_many :games_tournaments
  has_many :games, through: :games_tournaments
  has_many :participations, through: :games_tournaments
  has_many :users, through: :participations
  has_many :matchs, through: :participations

  has_attached_file :poster
  validates_attachment_content_type :poster, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  attr_accessible :name, :description, :street, :city, :state, :country, :max_players, :poster, :game_list, :recipient, :actor, :notifiable

  geocoded_by :address   # can also be an IP address
  after_validation :geocode      # auto-fetch coordinates

  def address
    [street, city, state, country].compact.join(', ')
  end

  def create_notifications(user)
    @user = user
    recipients.each do |recipient|
      #Notification.create(recipient: recipient, actor: @user,
       # action: 'posted', notifiable: self)
       @notif = Notification.new
       @notif.recipient = recipient
       @notif.actor = @user
       @notif.action = 'posted'
       @notif.notifiable = self
       @notif.save

    end
  end

  def game_list
    self.games.collect do |game|
      game.title
    end.join(", ")
  end

  def game_list=(games_string)
    games_titles = games_string[1..-1].split(",").collect{|s| s}
    found_games = games_titles.collect{|title| Game.where(title: title)}
    if !found_games.nil?
      found_games.each do |f|
        self.games += f
      end
    end
  end

  def recipients
    User.all
  end

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController

  def create
    @tournament = Tournament.new

    tournament_params_form

    User.all.each do |user|
      NotificationMailer.new_tournament_mail(user, @tournament).deliver
    end 

    flash.notice = "Tournament '#{@tournament.name}' Created!"
  end

  def destroy
    @tournament = Tournament.find(params[:id])

    @tournament.destroy

    redirect_to tournaments_path()

    flash.notice = "Tournament '#{@tournament.name}' Deleted!"
  end

  def edit
    @tournament = Tournament.find(params[:id])
  end

  def index
    @tournaments = Tournament.all
  end

  def new
    @tournament = Tournament.new
  end

  def simulate
    # Found all participations
    @tournament = Tournament.find(params[:tournament_id])
    
    @matches = @tournament.participations.combination(2).to_a

    cpt = 1.to_i

    @matches.each do |m|
      if(m[0].games_tournament_id == m[1].games_tournament_id)
        @match = Match.new
        @match.participation_id = m[0].id
        @match.participation2_id = m[1].id

        @match.result_of_match

        @match.participation.user.add_score = @match.score_user1
        @match.participation2.user.add_score = @match.score_user2

        @match.save 
      end     
    end

    @tournament.participations.each do |user|
      @gt = GamesTournament.find(user.games_tournament_id)
      @game = Game.find(@gt.game_id)
      @user = User.find(user.user_id)
      NotificationMailer.simulate_tournament_mail(@user, @tournament, @game).deliver
    end

    respond_to do |simulate|
      simulate.js {}
      simulate.html {redirect_to tournament_path(@tournament), notice:'#{@tournament.name} has been simulated!'}
    end 

    
  end

  def show
    @tournament = Tournament.find(params[:id])

    @has_been_simulated = @tournament.matchs.empty?

    puts "=================="
    puts @tournament.geocode

  end

  def update
    @tournament = Tournament.find(params[:id])

    tournament_params_form

    flash.notice = "Tournament '#{@tournament.name}' Updated!"
  end

  private
    def tournament_params_form
      @tournament.name = params[:tournament][:name]
      @tournament.description = params[:tournament][:description]
      @tournament.street = params[:tournament][:street]
      @tournament.city = params[:tournament][:city]
      @tournament.state = params[:tournament][:state]
      @tournament.country = params[:tournament][:country]
      @tournament.max_players = params[:tournament][:max_players]
      @tournament.poster = params[:tournament][:poster]
      @tournament.game_list = params[:tournament][:game_list]

      @tournament.save

      
      @tournament.create_notifications(current_user)

      redirect_to tournament_path(@tournament)
    end

end

app/helpers/tournaments_helper.rb
module TournamentsHelper

  def select_max_players_options
    [
      ['4', 4],
      ['8', 8],
      ['16', 16],
      ['32', 32],
      ['64', 64]
    ]
  end

  def select_games_options
    Game.all.collect {|g| [g.title, g.title]}
  end

end

app/views/tournaments/_form.html.haml
= form_for(@tournament, html: {multipart: true}) do |f|
  %ul
    - @tournament.errors.full_messages.each do |error|
      %li= error
  .form-group
    = f.label :name
    %br/
    = f.text_field :name
  .form-group
    = f.label :description
    %br/
    = f.text_area :description
  .form-group
    = f.select :max_players, select_max_players_options
  .form-group
    = f.label :street
    %br/
    = f.text_field :street
  .form-group
    = f.label :city
    %br/
    = f.text_field :city
  .form-group
    = f.label :state
    %br/
    = f.text_field :state
  .form-group
    = f.label :country
    %br/
    = f.text_field :country
  .form-group
    - if @tournament.poster.exists?
      = image_tag @tournament.poster.url
      %br/
    = f.label :poster, "Attach an Image"
    %br/
    = f.file_field :poster
  .form-group
    = f.label :game_list
    %br/
    = f.select :game_list, options_for_select(select_games_options, selected: "1" ), {}, { :multiple => true }
  %p
    = f.submit
- if @tournament.id.nil?
  = link_to "Back to Tournaments", tournaments_path()
- else
  = link_to "Back to Tournament", tournament_path(@tournament)

app/views/tournaments/_mtable.html.haml
List of matchs :
%table.table#tab-matches
  %thead
    %tr
      %th #
      %th Game
      %th 1st Player
      %th Score
      %th 2nd Player
  %tbody
    - @tournament.matchs.each do |m|
      %tr
        %td
          = m.id
        %td
          = link_to m.participation.games_tournament.game.title, game_path(m.participation.games_tournament.game)
        %td
          = link_to m.participation.user.username, user_path(m.participation.user)
        %td 
          = m.score_user1.to_s + " - " + m.score_user2.to_s
        %td
          = link_to m.participation2.user.username, user_path(m.participation2.user)

app/views/tournaments/edit.html.haml
%h3 Edit a tournament

= render partial: 'form'

app/views/tournaments/index.html.haml
%h3 All Tournaments

.row
  .col-md-6
    %ul.list-group
      - @tournaments.each do |tournament|
        %li.list-group-item
          = link_to tournament.name, tournament_path(tournament)
    - if can? :create, Tournament
      = link_to "Add a new tournament", new_tournament_path

app/views/tournaments/new.html.haml
%h3 Add a new tournament
= render partial: 'form'

app/views/tournaments/show.html.haml
%h3
  = @tournament.name
- if can? :manage, Tournament
  = link_to "edit", edit_tournament_path(@tournament)
  = link_to "delete", tournament_path(@tournament), method: :delete, data: {confirm: "Really delete the tournament?"}
  - if @has_been_simulated
    = link_to "simulate", tournament_simulate_path(@tournament), remote: true, id: "btn-simulate"

.container
  .row
    - if @tournament.poster.exists?
      = image_tag @tournament.poster.url
  .row
    = @tournament.description
  .row
    = @tournament.street + " " + @tournament.city + " " + @tournament.state + " " + @tournament.country

  .row
    List of games :
    - @tournament.games.each do |game|
      = link_to game.title, game_path(game)
  .row
    .col-md-6
      #matches-table
        -# Affichage du tableau des matchs
        = render partial: 'mtable'

  .row
    Map :
    %br/
    = image_tag "https://maps.googleapis.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@tournament.latitude}%2C#{@tournament.longitude}&key=AIzaSyB7khglydrnFFiSMwhDwCYX6u6x0_rkL1I"
= link_to "Back to Tournaments List", tournaments_path