config/routes.rb
RailsGame::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", confirmations: 'confirmations' }

  resources :dashboard
  resources :games do
    resources :ratings
  end
  resources :tournaments do
    get '/simulate' => 'tournaments#simulate'
  end
  resources :users
  resources :participations

  resources :notifications, only: [:index] do
    post :mark_as_read, on: :collection
    post :mark_as_read, on: :member
  end 

  get '/rankings' => 'users#ranking'

  root to: 'dashboard#index'
end

app/models/game.rb
class Game < ActiveRecord::Base

  has_many :games_tournaments
  has_many :tournaments, through: :games_tournaments
  has_many :participations, through: :games_tournaments
  has_many :users, through: :participations
  has_many :matchs, through: :participations
  has_many :ratings

  attr_accessible :title, :description, :genre, :image

  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  # All genres possible
  MOBA = 1.freeze
  STR = 2.freeze
  MMO = 3.freeze
  FPS = 4.freeze
  FIGHTING = 5.freeze

  def genre_string
    case self.genre
    when Game::MOBA
      "MOBA"
    when Game::STR
      "STR"
    when Game::MMO
      "MMO"
    when Game::FPS
      "FPS"
    else
      "Fighting"
    end
  end

  def to_s
    title
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def create
    @game = Game.new

    game_params_form

    flash.notice = "Game '#{@game.title}' Created!"
  end

  def destroy
    @game = Game.find(params[:id])

    @game.destroy

    redirect_to games_path()

    flash.notice = "Game '#{@game.title}' Deleted!"
  end

  def edit
    @game = Game.find(params[:id])
  end

  def index
    @games = Game.all
  end

  def new
    @game = Game.new
  end

  def show
    @game = Game.find(params[:id])

    @average = Rating.where(game_id: @game.id).average(:score)

    @rating = Rating.new
    @rating.game_id = @game.id
    if (!current_user.nil?)
      @rating.user_id = current_user.id    
      @has_voted = Rating.where(game_id: @rating.game_id, user_id: @rating.user_id).count()
    end
  end

  def update
    @game = Game.find(params[:id])

    game_params_form

    flash.notice = "Game '#{@game.title}' Updated!"
  end

  private
    def game_params_form
      @game.title = params[:game][:title]
      @game.description = params[:game][:description]
      @game.genre = params[:game][:genre]
      @game.image = params[:game][:image]

      @game.save

      redirect_to game_path(@game)
    end

end

app/helpers/games_helper.rb
module GamesHelper

  # Table with all the options for the form select or the genre
  def select_genre_options
    [
      ['MOBA', Game::MOBA],
      ['STR', Game::FPS],
      ['MMO', Game::MMO],
      ['FPS', Game::FPS],
      ['FIGHTING', Game::FIGHTING]
    ]
  end

end

app/views/games/_form.html.haml
= form_for(@game, html: {multipart: true}) do |f|
  %ul
    - @game.errors.full_messages.each do |error|
      %li= error
  .form-group
    = f.label :title
    %br/
    = f.text_field :title
  .form-group
    = f.label :description
    %br/
    = f.text_area :description
  .form-group
    = f.select :genre, select_genre_options
  .form-group
    - if @game.image.exists?
      = image_tag @game.image.url
      %br/
    = f.label :image, "Attach an Image"
    %br/
    = f.file_field :image
  %p
    = f.submit

- if @game.id.nil?
  = link_to "Back to Games", games_path()
- else
  = link_to "Back to Game", game_path(@game)

app/views/games/_rating.html.haml
%h5 Average Rating
= @average.round(2)

app/views/games/edit.html.haml
%h3 Edit a game

= render partial: 'form'

app/views/games/index.html.haml
%h3 All Games

.row
  .col-md-6
    %ul.list-group
      - @games.each do |game|
        %li.list-group-item
          = link_to game.title, game_path(game)
  - if can? :create, Game        
    = link_to "Add a new game", new_game_path

app/views/games/new.html.haml
%h3 Add a new game
= render partial: 'form'

app/views/games/show.html.haml
%h3
  = @game.title
- if can? :manage, Game
  = link_to "edit", edit_game_path(@game)
  = link_to "delete", game_path(@game), method: :delete, data: {confirm: "Really delete the game?"}

.container
  .row
    - if @game.image.exists?
      = image_tag @game.image.url
  .row
    = @game.description
  .row
    = @game.genre_string
  .row
    List of tournaments :
    - @game.tournaments.each do |tournament|
      = link_to tournament.name, tournament_path(tournament)
  .row
    %h3 Ratings
    - if @game.ratings.empty?
      Nobody voted yet
    - else 
      #average-result
        = render partial: 'games/rating'

    - if @has_voted == 0 && !current_user.nil?
      = render partial: 'ratings/form'
  

= link_to "Back to Games List", games_path